services:
  mongo:
    image: mongo
    restart: always
    # environment:
    # MONGO_INITDB_ROOT_USERNAME: root
    # MONGO_INITDB_ROOT_PASSWORD: something
    volumes:
      - mongovol:/data/db
    ports:
      - 37017:27017

  posts:
    image: friendpost-posts:latest
    ports:
      - 15001:8080
    environment:
      MONGO_URL: mongodb://mongo:27017/
      LISTEN_PORT: 8080

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8989:8081
    environment:
      # ME_CONFIG_MONGODB_ADMINUSERNAME: root
      # ME_CONFIG_MONGODB_ADMINPASSWORD: something
      ME_CONFIG_MONGODB_URL: mongodb://mongo:27017/
      ME_CONFIG_BASICAUTH: false

  eventbus:
    image: rabbitmq:3.13.3-management-alpine
    hostname: rmq
    volumes:
      - rmqvol:/var/lib/rabbitmq:rw
    ports:
      - 5672:5672
      - 15672:15672
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=something
      - RABBITMQ_ERLANG_COOKIE=chocochip

volumes:
  mongovol:
  rmqvol:
