services:
  mongo:
    image: mongo
    restart: always
    # environment:
    # MONGO_INITDB_ROOT_USERNAME: root
    # MONGO_INITDB_ROOT_PASSWORD: something
    volumes:
      - mongovol:/data/db
    ports:
      - 37017:27017

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8989:8081
    environment:
      # ME_CONFIG_MONGODB_ADMINUSERNAME: root
      # ME_CONFIG_MONGODB_ADMINPASSWORD: something
      ME_CONFIG_MONGODB_URL: mongodb://localhost:27017/
      ME_CONFIG_BASICAUTH: false

volumes:
  mongovol:
